name: ♻️ Refactor Request
description: Suggest code cleanup or architectural improvements.
labels: ["refactor"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a refactor!
        Please justify the **value** of this change (ROI) and how you plan to ensure **no regressions**.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: 📋 Prerequisites
      options:
        - label: I have checked existing issues to avoid duplicates.
          required: true

  - type: textarea
    id: target
    attributes:
      label: 🎯 Target Codebase
      description: What part of the codebase needs refactoring and why?
      placeholder: |
        - Module, file or component concerned
        - Technical debt or poor design patterns detected
        - Code smells or hard-to-test logic
        - Problems encountered during development or review
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 🧠 Motivation (ROI)
      description: Why is this refactor necessary? What is the gain?
      placeholder: |
        - Reduce technical debt (code is hard to understand).
        - Improve performance (current logic is O(n^2)).
        - Prepare codebase for upcoming Feature X.
        - Fix a recurring "code smell" (e.g., duplicated logic).
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: 🔧 Proposed Solution
      description: High-level plan of the refactor.
      placeholder: |
        - Extract the validation logic into a dedicated helper.
        - Implement the Strategy Pattern to handle different user types.
        - Rename variables to be more explicit.
    validations:
      required: true

  - type: textarea
    id: risk_analysis
    attributes:
      label: ⚠️ Risk & Regression Analysis
      description: A refactor should ideally NOT change behavior. What are the risks?
      placeholder: |
        - Risk: High. This module is used by the entire API.
        - Potential side effects on the login flow.
        - Requires updating the unit tests for X and Y.
    validations:
      required: true

  - type: checkboxes
    id: project_metadata
    attributes:
      label: 📂 Project Management (if applicable)
      description: If linked to a GitHub Project board, confirm metadata will be filled.
      options:
        - label: I confirm that I will fill in the required fields in the linked GitHub Project, if applicable.
