name: 🚀 Epic
description: A large initiative or project milestone that groups multiple related issues.
labels: ["epic"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### 🎯 Epic Tracking
        This issue tracks a high-level goal.
        Use the **Task List** below to:
        - Link existing child issues using `#issue_number`.
        - List new tasks (you can convert them to issues later by hovering over the line).

  - type: textarea
    id: objective
    attributes:
      label: 🎯 Objective
      description: What is the high-level goal of this Epic?
      placeholder: |
        - Implement the core logic for the data processing module.
        - Refactor the legacy system to improve performance.
        - Prepare the Release Candidate for v1.0.
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 🔨 Child Issues / Tasks
      description: >
        Link sub-tasks here. GitHub will automatically track progress based on checkboxes.
      placeholder: |
        - [ ] Define the software architecture
        - [ ] #42 (Link to an existing tracking issue)
        - [ ] Implement the main algorithm
        - [ ] Write documentation and unit tests
    validations:
      required: true
