name: 📌 Feature Request
description: Suggest a new idea, improvement, or enhancement.
title: "[FEATURE] : "
type: Feature

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to propose a new feature!
        Please fill out the form below to help us understand your idea.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: 📋 Prerequisites
      description: Please confirm you have completed these steps before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true

  - type: textarea
    id: goal
    attributes:
      label: 🎯 Goal
      description:
        Clearly state the purpose of this feature and the value it brings.
        Focus on the desired outcome rather than implementation details.
      placeholder: |
        - What is the intended outcome of this feature?
        - Who benefits from it and how?
        - What problem does it solve, or what opportunity does it create?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: ✅ Technical Steps
      description:
        Break down the technical steps required to implement the feature.
        Focus on logic, modules, services, or components involved. Use bullet points or numbered steps.
      placeholder: |
        - Step 1: Identify the modules or files that need to be modified
        - Step 2: Implement the necessary changes in the codebase
        - Step 3: Write integration/unit tests
        - Step 4: Update the documentation to reflect the new feature
    validations:
      required: false

  - type: textarea
    id: tests
    attributes:
      label: 🧪 Test Cases
      description: Describe how this feature will be tested. List realistic and meaningful test cases that cover expected behaviors, edge cases, and failure conditions.
      placeholder: |
        - Test Case 1: Describe the first test case
        - Test Case 2: Describe the second test case
        - Test Case 3: Describe the third test case
    validations:
      required: true

  - type: checkboxes
    id: project_compliance
    attributes:
      label: ✅ Project Integration
      description: Confirm that this issue includes the required project metadata.
      options:
        - label: I confirm that I have filled in all required fields in the GitHub Project (e.g. Priority, Status, Size, etc.)
          required: true